# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raziskava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_raziskave', models.CharField(max_length=200)),
                ('tip_raziskave', models.CharField(choices=[('DIPL', 'Diplomska naloga'), ('KLIN', 'Klinična farmakološka'), ('MP', 'Preverjanje medicinskega pripomočka'), ('DRUGO', 'Drugo')], max_length=200)),
                ('tip_raziskave_drugo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vlagatelj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('priimek', models.CharField(max_length=200)),
                ('sifra_arrs', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
