# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raziskava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov_raziskave_slo', models.TextField()),
                ('sifra_raziskave', models.CharField(blank=True, max_length=200)),
                ('tip_raziskave', models.CharField(choices=[('DIPL', 'Diplomska naloga'), ('KLIN', 'Klinična farmakološka'), ('MP', 'Preverjanje medicinskega pripomočka'), ('DRUGO', 'Drugo')], max_length=200)),
                ('tip_raziskave_drugo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'raziskave',
            },
        ),
        migrations.CreateModel(
            name='Vlagatelj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vlagatelji',
            },
        ),
        migrations.AddField(
            model_name='raziskava',
            name='vlagatelj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kme.Vlagatelj'),
        ),
    ]
