# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kme', '0003_auto_20170606_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raziskava',
            name='naslov_raziskave_slo',
            field=models.TextField(),
        ),
    ]
