# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kme', '0004_auto_20170606_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlagatelj',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vlagatelj',
            name='priimek',
        ),
        migrations.RemoveField(
            model_name='vlagatelj',
            name='sifra_arrs',
        ),
    ]
