# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kme', '0005_auto_20170607_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raziskava',
            name='sifra_raziskave',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
